test:
	go test -v -cover ./...

test_hash:
	go test -v -cover ./leetcode/hash_table/...

test_sorting:
	go test -v -cover ./leetcode/sorting/...

test_pointers:
	go test -v -cover ./leetcode/two_pointers/...

test_binary:
	go test -v -cover ./leetcode/binary_search/...

test_dfs_bfs:
	go test -v -cover ./leetcode/dfs_bfs/...

.PHONY: test test_hash test_sorting test_pointers test_dfs_bfs